name: Security Scan

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  checkov:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/security-checkov.yml@2.1.3
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'
