name: Security Scan

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@d27d2d3b49bcf14db85bdfb0f57956abf18bb091 # pinned to latest
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'
