name: Module Test Harness

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/stf-checks.yml@d27d2d3b49bcf14db85bdfb0f57956abf18bb091
    with:
      provider: digitalocean
      working_directory: ./_examples/complete/
