name: Tag Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: clouddrove/github-shared-workflows/.github/workflows/tag-release.yml@38cd6ebc01e8b5b14ac9a90a5579d04b02e79099 # pinned to latest
    with:
      target_branch: master
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
