name: 'Terratest GitHub Actions'
on:
  pull_request:
    branches:
      - master
    types: [labeled]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: 'Terratest'
        if: ${{ github.event.label.name == 'terratest' }}
        uses: 'clouddrove/github-actions@v9.0.1'
        with:
          actions_subcommand: 'terratest'
          tf_actions_working_dir: '_test'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DO_TOKEN: ${{ secrets.DO_TOKEN }}


